### ISSUE TITLE
Installation in Linux

### ISSUE THREAD

**Issue by LETRA** [haklein/certabo-lichess#5] opened 2020-03-16 06:36 UTC
Hello @haklein. I hope you're okay. I am testing the application on Linux (Elementary OS last version) and I have a couple of problems.  The first one is that it only recognizes the usb port if I launch the app with sudo. And when it runs it seems to be all right, but my movements are not transmitted to the game. My opponent's moves are, but mine are not. I've tried three times to create a new token with the option you indicate and I've also deleted from Lichess the setting required by the official Certabo app, but I can't get it to work as it did on Mac. The driver is loaded, the calibration is done, the board recognizes my moves, but Lichess doesn't see. Thank you in advance.

**Comment by haklein** [comment] 2020-03-16 07:05
@LETRA just to clarify, it works for you on Mac, or does it show the same behaviour there?
Regarding requiring sudo, your user is probably not in the `dialout` group. This is the usual group where you need to be member for serial access. Please re-test after adding your user to that group, and logging out/in.
If it still doesn't work, please attach the log file and also state your version numbers for python serial and python chess libraries.

**Comment by LETRA** [comment] 2020-03-16 15:58
Thanks @hacklein. Now, adding to the group, I can launch it without sudo. But lichess still doesn't see my movements. This is the command output in a game already started:

```
$ ./certabo-lichess.py
2020-03-16 16:32:40,738 INFO certabo-lichess certabo-lichess.py startup
2020-03-16 16:32:40,739 INFO codes codes.py - loading calibration
2020-03-16 16:32:40,739 INFO serialreader Auto-detecting serial port
2020-03-16 16:32:40,739 DEBUG serialreader Searching for port...
2020-03-16 16:32:40,740 DEBUG session stream GET https://lichess.org/api/stream/event params=None data=None json=None
2020-03-16 16:32:40,744 DEBUG connectionpool Starting new HTTPS connection (1): lichess.org:443
2020-03-16 16:32:40,758 DEBUG serialreader Trying /dev/ttyUSB0
2020-03-16 16:32:40,761 DEBUG serialreader Port is found! - /dev/ttyUSB0
2020-03-16 16:32:40,762 INFO serialreader Opening serial port /dev/ttyUSB0
2020-03-16 16:32:40,763 DEBUG serialreader Attempting to lock /dev/ttyUSB0
2020-03-16 16:32:40,763 DEBUG serialreader Flushing input on /dev/ttyUSB0
2020-03-16 16:32:40,876 DEBUG connectionpool https://lichess.org:443 "GET /api/stream/event HTTP/1.1" 200 None
2020-03-16 16:32:40,879 INFO certabo-lichess game start received: 8dtyMDsY
2020-03-16 16:32:40,879 DEBUG session stream GET https://lichess.org/api/board/game/stream/8dtyMDsY params=None data=None json=None
2020-03-16 16:32:40,885 DEBUG connectionpool Starting new HTTPS connection (2): lichess.org:443
2020-03-16 16:32:40,984 DEBUG connectionpool https://lichess.org:443 "GET /api/board/game/stream/8dtyMDsY HTTP/1.1" 200 None
2020-03-16 16:32:40,987 DEBUG session request GET https://lichess.org/api/account/playing params={'nb': 10} data=None json=None
2020-03-16 16:32:40,991 DEBUG connectionpool Starting new HTTPS connection (3): lichess.org:443
2020-03-16 16:32:42,776 INFO serialreader Exception during message decode: 'ascii' codec can't decode byte 0x91 in position 1: ordinal not in range(128)
2020-03-16 16:32:43,163 DEBUG connectionpool https://lichess.org:443 "GET /api/account/playing?nb=10 HTTP/1.1" 200 332
2020-03-16 16:32:43,165 INFO certabo-lichess setup_new_gameid() found gameId: 8dtyMDsY
2020-03-16 16:32:43,171 INFO certabo-lichess final FEN: rnbqkbnr/pppppppp/8/8/8/3P4/PPP1PPPP/RNBQKBNR b KQkq - 0 1
```

On Mac I also had problems after the first few moments when it worked fine. So running away from the driver problem I decided to install Linux on this old laptop and test if I can use the board without worry of failure.

One thing that is happening to me on all three operating systems (on two computers) is that sometimes when I disconnect and reconnect the cable the system suddenly shuts down and I have to restart.

**Comment by LETRA** [comment] 2020-03-16 16:07
Version numbers. Pyserial:

```
letra@MacBookAir2012:~/Aplicaciones/certabo-lichess-master$ pip3 show pyserial
Name: pyserial
Version: 3.4
Summary: Python Serial Port Extension
Home-page: https://github.com/pyserial/pyserial
Author: Chris Liechti
Author-email: cliechti@gmx.net
License: BSD
Location: /home/letra/.local/lib/python3.6/site-packages
Requires: 
```

And python-chess:

```
letra@MacBookAir2012:~/Aplicaciones/certabo-lichess-master$ pip3 show python-chess
Name: python-chess
Version: 0.24.1
Summary: A pure Python chess library with move generation and validation, Polyglot opening book probing, PGN reading and writing, Gaviota tablebase probing, Syzygy tablebase probing and XBoard/UCI engine communication.
Home-page: https://github.com/niklasf/python-chess
Author: Niklas Fiekas
Author-email: niklas.fiekas@backscattering.de
License: GPL3
Location: /home/letra/.local/lib/python3.6/site-packages
Requires: 
```

**Comment by haklein** [comment] 2020-03-16 20:08
@LETRA it works perfect for me on a (quite powerful) Lenovo Thinkpad:
~~~
$ pip3 show pyserial
Name: pyserial
Version: 3.4
Summary: Python Serial Port Extension
Home-page: https://github.com/pyserial/pyserial
Author: Chris Liechti
Author-email: cliechti@gmx.net
License: BSD
Location: /home/hklein/.local/lib/python3.7/site-packages
Requires: 
Required-by: pygatt

$ pip3 show python-chess
Name: python-chess
Version: 0.23.11
Summary: A pure Python chess library with move generation and validation, Polyglot opening book probing, PGN reading and writing, Gaviota tablebase probing, Syzygy tablebase probing and XBoard/UCI engine communication.
Home-page: https://github.com/niklasf/python-chess
Author: Niklas Fiekas
Author-email: niklas.fiekas@backscattering.de
License: GPL3
Location: /home/hklein/.local/lib/python3.7/site-packages
Requires: 
Required-by: 

$ uname -a
Linux notebook.localdomain 5.4.10-200.fc31.x86_64 #1 SMP Thu Jan 9 19:58:12 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

$ cat /etc/fedora-release 
Fedora release 31 (Thirty One)

$ python -V
Python 3.7.6
~~~

But I'm able to reproduce the behaviour you mention on a Rapsberry Pi Zero W. Apparently it's not the python-chess version, I've downgraded that already. I'll have a thorough look and will keep you posted.

**Comment by LETRA** [comment] 2020-03-16 20:20
Thank you. I add the missing data about the kernel:

```
letra@MacBookAir2012:~$ uname -a
Linux MacBookAir2012 5.3.0-40-generic #32~18.04.1-Ubuntu SMP Mon Feb 3 14:05:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

```
letra@MacBookAir2012:/etc$ cat /etc/lsb-release
DISTRIB_ID=elementary
DISTRIB_RELEASE=5.1.2
DISTRIB_CODENAME=hera
DISTRIB_DESCRIPTION="elementary OS 5.1.2 Hera"

```

I think there may be a problem here. Although I successfully installed python 3 and pip3 then I installed pip to test one of the UCI engine management programs you recommend.

```
letra@MacBookAir2012:/etc$ python -V
Python 2.7.17
```

**Comment by haklein** [comment] 2020-03-16 20:26
the certabo-lichess.py script should invoke python3 (see the first line). It would probably fail with SyntaxError when being run with python2.
I'm just digging into the problem.

**Comment by haklein** [comment] 2020-03-16 21:51
@LETRA the reason is apparently a blatant waste of resources. Watching the script on the RPi Zero quickly made apparenty that it's using a lot of CPU. Part of that is from serial polling, which isn't even required. I can well use blocking reads in the serial thread. That part is fixed. It's now already kind of "playable" on the RPi. But I do also waste a lot of cycles when attempting to find out if a move did happen on the board. I'm just addressing this.

**Comment by LETRA** [comment] 2020-03-16 22:45
@hacklein My knowledge of Linux is at the user level, not at the developer, but I will try to be helpful. When you want me to test something, let me know.  I may not have the same behavior on the RPi and this laptop with Elementary.

**Comment by haklein** [comment] 2020-03-17 00:08
@LETRA I'd appreciate if you could give the `wip-move-event` branch a try. While this is quite fresh and still might have some rough edges, it's giving quite good results for me already on the raspberry. It includes further serial optimisation, uses events to notify about new moves, and faster move detection.

**Comment by LETRA** [comment] 2020-03-17 00:30
[edit: I used the new files with changes but not wipe-move-event]

It looks like the same thing is happening:

```
letra@MacBookAir2012:~/Aplicaciones/certabo-lichess-master$ ./certabo-lichess.py 
2020-03-17 01:22:29,157 INFO certabo-lichess certabo-lichess.py startup
2020-03-17 01:22:29,157 INFO codes codes.py - loading calibration
2020-03-17 01:22:29,158 INFO serialreader Auto-detecting serial port
2020-03-17 01:22:29,158 DEBUG serialreader Searching for port...
2020-03-17 01:22:29,159 DEBUG certabo-lichess board event loop
2020-03-17 01:22:29,159 DEBUG session stream GET https://lichess.org/api/stream/event params=None data=None json=None
2020-03-17 01:22:29,162 DEBUG connectionpool Starting new HTTPS connection (1): lichess.org:443
2020-03-17 01:22:29,176 DEBUG serialreader Trying /dev/ttyUSB0
2020-03-17 01:22:29,179 DEBUG serialreader Port is found! - /dev/ttyUSB0
2020-03-17 01:22:29,179 INFO serialreader Opening serial port /dev/ttyUSB0
2020-03-17 01:22:29,181 DEBUG serialreader Attempting to lock /dev/ttyUSB0
2020-03-17 01:22:29,181 DEBUG serialreader Flushing input on /dev/ttyUSB0
2020-03-17 01:22:29,320 DEBUG connectionpool https://lichess.org:443 "GET /api/stream/event HTTP/1.1" 200 None
2020-03-17 01:22:29,322 INFO certabo-lichess game start received: TiAgvW2L
2020-03-17 01:22:29,323 DEBUG session stream GET https://lichess.org/api/board/game/stream/TiAgvW2L params=None data=None json=None
2020-03-17 01:22:29,326 DEBUG connectionpool Starting new HTTPS connection (2): lichess.org:443
2020-03-17 01:22:29,427 DEBUG connectionpool https://lichess.org:443 "GET /api/board/game/stream/TiAgvW2L HTTP/1.1" 200 None
2020-03-17 01:22:29,430 DEBUG session request GET https://lichess.org/api/account/playing params={'nb': 10} data=None json=None
2020-03-17 01:22:29,434 DEBUG connectionpool Starting new HTTPS connection (3): lichess.org:443
2020-03-17 01:22:31,665 DEBUG connectionpool https://lichess.org:443 "GET /api/account/playing?nb=10 HTTP/1.1" 200 332
2020-03-17 01:22:31,667 INFO certabo-lichess setup_new_gameid() found gameId: TiAgvW2L
2020-03-17 01:22:31,668 INFO certabo-lichess final FEN: rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq - 0 1
2020-03-17 01:22:31,669 INFO certabo-lichess starting new game, checking for user move
```
And if I try to recalibrate
```
(...)
2020-03-17 01:29:15,643 INFO codes previous in current
2020-03-17 01:29:15,643 INFO codes Q after = [[85, 0, 11, 155, 47]]
2020-03-17 01:29:15,643 INFO codes ------- not new setup ----
2020-03-17 01:29:15,643 INFO serialreader Exception during message decode: [Errno 13] Permission denied: '/home/letra/.local/share/GUI/calibration.bin'
2020-03-17 01:29:15,654 INFO certabo     adding new calibration sample
2020-03-17 01:29:15,654 INFO certabo ------- we have collected enough samples for averaging ----
2020-03-17 01:29:17,744 INFO codes Q before = [[85, 0, 11, 155, 47]]
2020-03-17 01:29:17,744 INFO codes previous in current
(...)
```

**Comment by LETRA** [comment] 2020-03-17 00:42
With "wipe-move-event" branch:

```
letra@MacBookAir2012:~/Aplicaciones/certabo-lichess-wip-move-event$ ./certabo-lichess.py 
2020-03-17 01:41:56,729 INFO certabo-lichess certabo-lichess.py startup
2020-03-17 01:41:56,729 INFO codes codes.py - loading calibration
2020-03-17 01:41:56,730 INFO serialreader Auto-detecting serial port
2020-03-17 01:41:56,730 DEBUG serialreader Searching for port...
2020-03-17 01:41:56,731 DEBUG certabo-lichess board event loop
2020-03-17 01:41:56,731 DEBUG session stream GET https://lichess.org/api/stream/event params=None data=None json=None
2020-03-17 01:41:56,734 DEBUG connectionpool Starting new HTTPS connection (1): lichess.org:443
2020-03-17 01:41:56,747 DEBUG serialreader Trying /dev/ttyUSB0
2020-03-17 01:41:56,750 DEBUG serialreader Port is found! - /dev/ttyUSB0
2020-03-17 01:41:56,750 INFO serialreader Opening serial port /dev/ttyUSB0
2020-03-17 01:41:56,751 DEBUG serialreader Attempting to lock /dev/ttyUSB0
2020-03-17 01:41:56,751 DEBUG serialreader Flushing input on /dev/ttyUSB0
2020-03-17 01:41:56,893 DEBUG connectionpool https://lichess.org:443 "GET /api/stream/event HTTP/1.1" 200 None
2020-03-17 01:41:56,895 INFO certabo-lichess game start received: TiAgvW2L
2020-03-17 01:41:56,896 DEBUG session stream GET https://lichess.org/api/board/game/stream/TiAgvW2L params=None data=None json=None
2020-03-17 01:41:56,900 DEBUG connectionpool Starting new HTTPS connection (2): lichess.org:443
2020-03-17 01:41:57,004 DEBUG connectionpool https://lichess.org:443 "GET /api/board/game/stream/TiAgvW2L HTTP/1.1" 200 None
2020-03-17 01:41:57,006 DEBUG session request GET https://lichess.org/api/account/playing params={'nb': 10} data=None json=None
2020-03-17 01:41:57,011 DEBUG connectionpool Starting new HTTPS connection (3): lichess.org:443
2020-03-17 01:41:59,001 DEBUG connectionpool https://lichess.org:443 "GET /api/account/playing?nb=10 HTTP/1.1" 200 332
2020-03-17 01:41:59,003 INFO certabo-lichess setup_new_gameid() found gameId: TiAgvW2L
2020-03-17 01:41:59,005 INFO certabo-lichess final FEN: rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq - 0 1
2020-03-17 01:41:59,006 INFO certabo-lichess starting new game, checking for user move
2020-03-17 01:41:59,006 DEBUG certabo waiting for event signal
2020-03-17 01:41:59,075 DEBUG certabo trying to find user move in usb data
2020-03-17 01:41:59,080 DEBUG codes Unable to detect moves

```

**Comment by LETRA** [comment] 2020-03-17 00:46
Another detail, is that in the last attempts I can't finish the output of the command without closing the terminal window.

**Comment by haklein** [comment] 2020-03-17 13:48
@LETRA apparently the calibration file is still owned by root from your previous attempts, leading to this error:
~~~
2020-03-17 01:29:15,643 INFO serialreader Exception during message decode: [Errno 13] Permission denied: '/home/letra/.local/share/GUI/calibration.bin'
~~~
Please make sure that you have write permissions the GUI directory and that the files therein belong to your user.

**Comment by LETRA** [comment] 2020-03-17 19:27
The folder had permissions, but for some reason the .bin file didn't. Now worked fine. No console error messages. I was able to play the game without any problems. I disconnected the cable to see if there was an error in the reconnection. The game continued correctly.  I will leave this version unchanged, but if you make modifications I will try them too in other folder. 

Just one question for the moment: is there any way to use addpiece in the calibration?

**Comment by haklein** [comment] 2020-03-17 20:04
@LETRA that's great to hear! Thanks for the feedback. I'll add AddPiece in a bit. The code is there, just missing a commandline parameter.

**Comment by haklein** [comment] 2020-03-17 20:33
@LETRA I've merged `wip-move-event` into the master branch, and I've added the --addpiece switch there.

**Comment by LETRA** [comment] 2020-03-17 23:51
I found a problem here. It says `DEBUG certabo trying to find user move in usb data` and I can't turn the pawn into Queen.

```
2020-03-18 00:44:07,585 DEBUG certabo trying to find user move in usb data
2020-03-18 00:44:07,588 DEBUG codes Single move detected - g2g4
2020-03-18 00:44:07,588 DEBUG certabo firing event
2020-03-18 00:44:07,589 DEBUG certabo event signal received, pending moves: ['g2g4']
2020-03-18 00:44:07,589 INFO certabo-lichess our move: ['g2g4']
2020-03-18 00:44:07,589 DEBUG session request POST https://lichess.org/api/board/game/TyNLVcdt/move/g2g4 params=None data=None json=None
2020-03-18 00:44:07,592 DEBUG connectionpool Resetting dropped connection: lichess.org
2020-03-18 00:44:08,344 DEBUG connectionpool https://lichess.org:443 "POST /api/board/game/TyNLVcdt/move/g2g4 HTTP/1.1" 200 11
{'type': 'gameState', 'moves': 'd2d4 e7e6 b1c3 f8b4 c1d2 b8c6 e2e3 g8e7 g1f3 d7d5 f1b5 c8d7 e1g1 a7a6 b5a4 e8g8 f1e1 e7g6 e3e4 g6e7 e4d5 e6d5 a2a3 b4c3 d2c3 e7g6 a4b3 d7f5 f3e5 f5e6 e5g6 e6g4 f2f3 f7g6 f3g4 f8f4 h2h3 d8h4 b3d5 g8f8 d5c6 h4f2 g1h2 a8b8 c3b4 f8f7 e1e7 f7g8 c6d5 g8h8 d1e1 f2e1 a1e1 h7h6 e7e8 b8e8 e1e8 h8h7 d5b7 f4d4 e8e7 h6h5 g4h5 d4c4 h5g6 h7h6 b4d2 h6g6 b7a6 g6f6 e7e2 c4c6 d2c3 f6g5 a6c8 c6g6 a3a4 g5h4 a4a5 h4g5 a5a6 g5h4 a6a7 g6g2 e2g2 g7g5 g2g4', 'wtime': datetime.datetime(1970, 1, 25, 20, 31, 23, 647000, tzinfo=datetime.timezone.utc), 'btime': datetime.datetime(1970, 1, 25, 20, 31, 23, 647000, tzinfo=datetime.timezone.utc), 'winc': datetime.datetime(1970, 1, 1, 0, 0, tzinfo=datetime.timezone.utc), 'binc': datetime.datetime(1970, 1, 1, 0, 0, tzinfo=datetime.timezone.utc), 'wdraw': False, 'bdraw': False, 'status': 'started'}
{'type': 'gameState', 'moves': 'd2d4 e7e6 b1c3 f8b4 c1d2 b8c6 e2e3 g8e7 g1f3 d7d5 f1b5 c8d7 e1g1 a7a6 b5a4 e8g8 f1e1 e7g6 e3e4 g6e7 e4d5 e6d5 a2a3 b4c3 d2c3 e7g6 a4b3 d7f5 f3e5 f5e6 e5g6 e6g4 f2f3 f7g6 f3g4 f8f4 h2h3 d8h4 b3d5 g8f8 d5c6 h4f2 g1h2 a8b8 c3b4 f8f7 e1e7 f7g8 c6d5 g8h8 d1e1 f2e1 a1e1 h7h6 e7e8 b8e8 e1e8 h8h7 d5b7 f4d4 e8e7 h6h5 g4h5 d4c4 h5g6 h7h6 b4d2 h6g6 b7a6 g6f6 e7e2 c4c6 d2c3 f6g5 a6c8 c6g6 a3a4 g5h4 a4a5 h4g5 a5a6 g5h4 a6a7 g6g2 e2g2 g7g5 g2g4 h4h5', 'wtime': datetime.datetime(1970, 1, 25, 20, 31, 23, 647000, tzinfo=datetime.timezone.utc), 'btime': datetime.datetime(1970, 1, 25, 20, 31, 23, 647000, tzinfo=datetime.timezone.utc), 'winc': datetime.datetime(1970, 1, 1, 0, 0, tzinfo=datetime.timezone.utc), 'binc': datetime.datetime(1970, 1, 1, 0, 0, tzinfo=datetime.timezone.utc), 'wdraw': False, 'bdraw': False, 'status': 'started'}
2020-03-18 00:44:10,231 INFO certabo-lichess it is our turn
2020-03-18 00:44:10,231 DEBUG certabo waiting for event signal
2020-03-18 00:44:19,404 DEBUG certabo trying to find user move in usb data
2020-03-18 00:44:19,409 DEBUG codes Unable to detect moves

```

**Comment by haklein** [comment] 2020-03-18 06:58
@LETRA that's interesting, promotion used to work in the past. Maybe that relates to the one move depth limit I've applied to the move detection to be quicker I've raised ticket #8 and will look at that today.

**Comment by LETRA** [comment] 2020-03-18 23:15
Now the problem of the port has returned

```
2020-03-19 00:08:53,537 INFO certabo-lichess certabo-lichess.py startup
2020-03-19 00:08:53,538 INFO codes codes.py - loading calibration
2020-03-19 00:08:53,538 INFO serialreader Auto-detecting serial port
2020-03-19 00:08:53,538 DEBUG serialreader Searching for port...
2020-03-19 00:08:53,539 DEBUG certabo-lichess board event loop
2020-03-19 00:08:53,539 DEBUG session stream GET https://lichess.org/api/stream/event params=None data=None json=None
2020-03-19 00:08:53,542 DEBUG connectionpool Starting new HTTPS connection (1): lichess.org:443
2020-03-19 00:08:53,556 DEBUG serialreader Port not found
2020-03-19 00:08:53,557 INFO serialreader No port found, retrying
2020-03-19 00:08:53,641 DEBUG connectionpool https://lichess.org:443 "GET /api/stream/event HTTP/1.1" 200 None
2020-03-19 00:08:53,644 INFO certabo-lichess game start received: el6xuRd9
2020-03-19 00:08:53,644 DEBUG session stream GET https://lichess.org/api/board/game/stream/el6xuRd9 params=None data=None json=None
2020-03-19 00:08:53,646 DEBUG connectionpool Starting new HTTPS connection (2): lichess.org:443
2020-03-19 00:08:53,767 DEBUG connectionpool https://lichess.org:443 "GET /api/board/game/stream/el6xuRd9 HTTP/1.1" 200 None
2020-03-19 00:08:53,770 DEBUG session request GET https://lichess.org/api/account/playing params={'nb': 10} data=None json=None
2020-03-19 00:08:53,772 DEBUG connectionpool Starting new HTTPS connection (3): lichess.org:443
2020-03-19 00:08:54,557 INFO serialreader Auto-detecting serial port
2020-03-19 00:08:54,558 DEBUG serialreader Searching for port...
2020-03-19 00:08:54,573 DEBUG serialreader Port not found
2020-03-19 00:08:54,573 INFO serialreader No port found, retrying
2020-03-19 00:08:55,574 INFO serialreader Auto-detecting serial port
2020-03-19 00:08:55,575 DEBUG serialreader Searching for port...
2020-03-19 00:08:55,592 DEBUG serialreader Port not found
2020-03-19 00:08:55,592 INFO serialreader No port found, retrying
2020-03-19 00:08:55,789 DEBUG connectionpool https://lichess.org:443 "GET /api/account/playing?nb=10 HTTP/1.1" 200 326
2020-03-19 00:08:55,791 INFO certabo-lichess setup_new_gameid() found gameId: el6xuRd9
2020-03-19 00:08:55,792 INFO certabo-lichess final FEN: rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1
2020-03-19 00:08:55,793 INFO certabo-lichess starting new game, checking for user move
2020-03-19 00:08:55,793 DEBUG certabo waiting for event signal
2020-03-19 00:08:56,593 INFO serialreader Auto-detecting serial port
2020-03-19 00:08:56,594 DEBUG serialreader Searching for port...
2020-03-19 00:08:56,608 DEBUG serialreader Port not found
2020-03-19 00:08:56,608 INFO serialreader No port found, retrying
2020-03-19 00:08:57,609 INFO serialreader Auto-detecting serial port
2020-03-19 00:08:57,610 DEBUG serialreader Searching for port...
2020-03-19 00:08:57,626 DEBUG serialreader Port not found
2020-03-19 00:08:57,627 INFO serialreader No port found, retrying
2020-03-19 00:08:58,628 INFO serialreader Auto-detecting serial port
2020-03-19 00:08:58,629 DEBUG serialreader Searching for port...
2020-03-19 00:08:58,646 DEBUG serialreader Port not found
```

**Comment by haklein** [comment] 2020-03-20 07:44
@LETRA that does look like if no serial port were available. The code just uses the "official" pyserial tools code to iterate serial ports.. that's nothing specific to my code. Did you plug the magnetic cable connector the proper way round? It fits two ways, but only one way ensures USB connectivity (the LED on the plug needs to point upwards)

**Comment by LETRA** [comment] 2020-03-20 21:26
Yes, I connect it well. I think I have an item with a defect. The board randomly gives the usb port problem on three different operating systems and three different computers. I have written to Pietro and he proposes me to disassemble the connector of the board and send me a new cable, but I am not very happy with it.

**Comment by haklein** [comment] 2020-03-20 21:48
I'm unsure right now if the magnetic plug can be removed from the port. As far as I've understood this is just a USB micro cable with magnetic plug. If the plug can be removed, you could try with a regular USB cable..

**Comment by LETRA** [comment] 2020-03-22 00:10
@haklein That's what Pietro told me. Right now I've written to him and sent him a couple more pictures.

**Closed as completed** 2020-04-01 11:28 UTC
